name: Swift

on: pull_request

jobs:
  build:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
    - run: git lfs checkout
    - name: Build
      run: swift build -v
    - run: mkdir test-results
    - name: Run tests
      run: swift test -v --xunit-output test-results/test.xml --parallel
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: always()
      with:
        files: test-results/**/*.xml
